[profile.default]
src = "src"
out = "out"
libs = ["lib"]
dotenv = true

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    'forge-std=lib/forge-std/src',
    'lib/forge-std/src=lib/forge-std/src',
    'lib/forge-std=lib/forge-std'
]

[lint]
exclude_lints = ["asm-keccak256"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
